Name:           ros-indigo-innok-heros-control
Version:        1.0.3
Release:        0%{?dist}
Summary:        ROS innok_heros_control package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/Robots/Innok-Heros
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-controller-manager
Requires:       ros-indigo-innok-heros-description
Requires:       ros-indigo-innok-heros-gazebo
Requires:       ros-indigo-joy
Requires:       ros-indigo-teleop-twist-joy
Requires:       ros-indigo-teleop-twist-keyboard
Requires:       ros-indigo-twist-mux
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-roslaunch

%description
package to control the Innok Heros with several devices (e. g. joystick and
keyboard)

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Dec 11 2015 Sabrina Heerklotz <sh@innok-robotics.de> - 1.0.3-0
- Autogenerated by Bloom

